* 大部分课程都是白学
  没错，大家十之八九以后不会搞开发，更不会搞系统开发。那么这些系统知识对你来讲的确是白学。不过，大家也该再想想，你学过的哪些知识将会是你以后用得到的？算数、语文、英语，我看也就这三门了。那么剩下的都是白学吗？的确，极有可能都是白学。“那么还逼着我学这些干吗？马马虎虎过去算了”。我早说过了，你来上学要获得的不止是知识。也就是说，除了算数语文英语，还有一样东西是你以后肯定要用到的，那就是能力---思维、学习的能力。

: 算数+语文+英语+能力 = 基础知识 + 能力 = 素质

  能力，是大学教育的核心。学林学的，无非就是把林学知识做为能力训练的工具；学经济管理的，无非就是把管理知识做为能力训练的工具；学计科的，无非就是把计算机知识做为能力训练的工具。

  能力训练就是学习的过程，是一个痛苦的过程。不管你有兴趣还是没兴趣，想有能力就必须痛苦地训练。

* 学习吃力最主要的原因就是负债太多
  捷径问题
* 学生有三个等级
  在我看，学生有三种：
  1. 懂道理，并且按道理做事情；
  2. 懂道理，但不按道理做事情（主要是因为懒惰）；
  3. 自创一个伪道理，以便于能心安理得地不按道理做事情（这就是人品问题了）。
* 如何选择毕业设计题目
  一个坏主意的开始通常是“这个容易，我会做”；而一个好主意的开始通常是“这个有趣，我想做”。
* 大学和技校的区别
  在我看，大学和技校的区别就在于
  - 大学注重讲道理，讲原理，锻炼思考、分析的能力。在讲道理的过程中肯定会用到某些具体的技术，比如讲《计算机科学与编程导论》的时候，我们就要用到Python，自然就要学一下Python。但Python的语法技巧并不是这门课的核心内容。
  - 而技校正好相反。技校注重教“手艺”。在学习“手艺”的过程中，总会遇到一些重要的道理、原理，于是就要顺带介绍一下这些个理论性的东西。

  另外，我觉得思想、思维训练的比例不应该缩减，而应该逐步加大。因为这就是大学和技校的区别。学一门手艺，混一个饭碗，这是技校教育的目标。做为大学生去和技校生拼手艺，这本身就是很失败的事情。大学生的优势应该在于有一个更会思考的大脑，也就有了一个更好的发展基础。在这个基础上，他应该有更好的发展前景和空间。

  我坚决反对打着知识的旗号把大学办成技校。而实际我们过去的这些年就是这么做的。效果如何呢？学风日下，教风日下。教师骂学生基础太差，提不起来；学生骂教师敷衍了事，文凭贩子。

  在我看，学生骂教师“敷衍了事，文凭贩子”一点都没错。因为我们就是在卖文凭，在敷衍。而教师抱怨学生“基础差，没法教”就很牵强。在我看，他们抱怨的目的只是在为自己的敷衍找一个貌似合理的借口而已。教师的本份就是让学生在四年后变得不再象刚入学时那样差。可是我们根本没做到，甚至没做！04级的唐章军告诉我，他们班现在搞技术的只有他和严兴秀两人而已。这就是“没做”的证明！

  的确，画画、练武、打球都要强调基本功。我很喜欢你打的这些比方，只是你把什么是“基础”，什么是“招式”搞反了。比如，拿编程来讲，语法就是招式，"Hello, world"就是你说的花拳秀腿。什么是基本功？正是我们说的“思维能力的培养”。如果你注重基本功的话，那么显然就是要注重“思维能力的培养”了。当然，花拳秀腿也不是全然无用，每天多比划比划，的确也可以加深对“功夫”的理解，日子久了也会长进的。但这不能成为教师教花拳秀腿的理由。

  技校教育，饭碗教育，就是典型的花拳秀腿教育。其本质就是让教师花尽量少的精力使学生掌握基本的花拳秀腿，以便于去街头卖艺，蒙碗饭吃。

  大学教育应该注重的，就是你说的“基础”。但基础不是语法、指令、格式……，而是算数、语文、英语、和思维。这些东西就叫“素质”。素质是各门学科所共同依赖的东西，也就是基础。很多教师认为算数语文英语不是自己的事情。好吧，就算这些东西是入学就该具备的，那么思维你总该负责吧？把“招式”当做基础来教，这就本末倒置了。只教拳，不教功，这是黄蓉对待杨过的做法嘛。而欧阳锋就不同，他教杨过的招式难看得象蛤蟆，但功夫是实实在在的。欧阳锋对干儿子的态度才算是认真负责的嘛。（不认识黄蓉、杨过、欧阳锋的老师请参阅《神雕侠侣》）

  说到“干儿子”，我就想到诸位老师差不多都有了自己的孩子。如果你的孩子在这儿上学，你会怎么教？大家都是明白人，面对的不过是个良心问题而已。

  我说过了，“饭碗教育”是消极教育，它的消极性会带来学生学习的消极性。学习的消极性会导致学生连基本的花拳秀腿都掌握不了。这才是威胁学生饭碗的根本原因。要消除“饭碗危机”，就要推行“积极教育”，也就是“思维教育，能力教育”，因为决定饭碗的不是“知识”，而是“能力和态度”，只有积极教育才能训练出能力和态度。

  也许你会问，技校生不都是“饭碗教育”的产物吗？他们不都有不错的饭碗吗？的确是这样，但这不适用于大学。因为技校卖“手艺”，不卖“文凭”，学到手艺才能毕业。而大学卖文凭，屁都不会的学生也能毕业，这直接导致学生没压力。在没压力的情况下，饭碗教育还在向学生传递“一招鲜，吃遍天”，“多学无用”这样的情绪，他怎么可能有心思学“手艺”呢？所以说，我们现在只能是一个失败的技校。

  再说说“中国国情”。所谓“中国国情”，实际上就是“中国弊端”的代名词罢了，除非你能给我举出几个不是弊端的国情来。既然是弊端，那么就该改变它，而不是顺应它。教育的目的不是为了培养“垃圾国情”的继承者、维护者，而是为了培养改良者和进步者。如果教师只知道顺应“国情”的话，那么教育就只剩下悲哀了，中国人就只好世世代代享受这“酱缸国情”了。
* 积极教学与消极教学
  我觉得大学教育应该首先注重能力 --- 思维、创新、独立思考的能力。所谓大学就是“博大的学问”，意义就在于“博”和“大”，在于开拓眼界，开放思想。别告诉我说这观念太过理想化，其实这观念深深地印在我们每个人的心中。包括你、我、学生，甚至民工心里都是这么想的。

  不信，你可以去问问毕业生，他为什么不去建筑工地搬砖？因为他觉得自己接受过大学教育，应该有比民工更高一些的东西。这“更高一些的东西”是什么？不就是思维和能力嘛。

  可糟糕的是我们的教学在很大程度上忽视了“思维和能力”的训练，从来就是以“饭碗思维”为主导。思维的乐趣，大学的意义，被我们远远地丢到一边了。“博大的学问”听起来很美好，很浪漫。学生都去漫无目的地博览群书了，就业怎么办？饭碗怎么办？能问出这种问题，就说明你根本没动脑子。威胁到“饭碗”的不是看闲书，而是不看书。换言之，就是懒惰。学生为什么懒惰？或者更直接地说，为什么我们的学生格外的懒惰？原因之一就是，从大一进校门开始，我们的教师就在给学生灌输“饭碗思维”，灌输所谓“一招鲜，吃遍天”。既然一招鲜就够了，那还学习那么多干什么？当这种“多学无用”的态度被潜移默化地传递给学生的时候，“这门课没用，我不学”，“那门课没兴趣，我也不学”的现象就泛滥开了。而且不学习有了充分的理由，“因为没用，没兴趣”嘛。于是懒惰成了天经地义的事情。就是这种“天经地义”的态度才真正威胁到了学生的饭碗。

  所以我说，“饭碗教学”是一种消极教学，它只能让学生跟着你一起消极。而“思维教学”，“能力教学”是一种积极教学，它不仅是在教“知识”，更是在教“态度”。
  有了能力，有了态度，获得“手艺”又有何难？你见过哪个有脑子，有素质的人被饿死吗？民工都饿不死，何况一个大学生呢？既然饿不死，“饭碗教学”又意义何在呢？
