#+TITLE:     随感
#+AUTHOR:    王晓林
#+EMAIL:     wx672ster@gmail.com
#+LANGUAGE:  cn
#+OPTIONS:   H:3 num:3 toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:plain toc:t ltoc:t mouse:underline buttons:0 path:nil
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* 读书								   :noexport:
  - 发财 饭碗 黄金屋
  - 李宏志 Bill Gates
  - 上印刷品的当
  - 开拓视野 学会思考 监听则明
* 迷茫
  很多同学都说自己很迷茫，不知道为什么上学，不知道该学些什么，不知道该向哪个方向发展，不知道以后要去干什么，不知道……他们在一连串的“不知道”中迷茫。但在迷茫中，他们却知道了玩游戏，知道了睡懒觉，知道了抽烟喝酒，知道了旷课逃学，知道了……总之，除了学习，他们什么都知道了。
  
  为什么放弃学习？因为我迷茫，不知道该学什么。你当老师的，又不能帮我摆脱迷茫，不能给我指明方向，那我怎么学习？好了，老师，你也别委屈，的确，你们给我指方向了，可你们那么多老师，一人指一个方向，都把我指晕了，我还是不知道该望那边走啊。所以即使学了，也很可能学错了，还不如省点力气，先混个文凭，等以后上了班，要用到什么再现学吧。理由充分，设想完美！

  现在轮到我为自己辩白了。作为教师，我的工作之一就是站在十字路口上，告诉你哪条路通往什么方向。一人指一个方向也不奇怪，各位教师的兴趣方向本就不同嘛。那么，你该走那条路呢？作为成年人的你，有选择的权利和自由。

  小的时候，我们都很羡慕成年人的自由，想干嘛就干嘛。恨自己长得太慢，恨不能去吃点激素化肥，快些长大，摆脱家长老师的指手画脚，按自己的想法来肆意折腾。现在好了，你真的长出了胡子，成年了。你有了自由选择的权利，轮到你“肆意”了，而你却“迷茫”了，没了主意。你有了自由，你喜欢自由，因为自由能让你玩游戏、睡懒觉、旷课逃学、抽烟喝酒……能让你享受颓废。人都是有惰性的，所以颓废真的很舒服。

  但舒服完了心情并不好，为什么？如果你看过《蜘蛛侠》的话，应该对这句台词有印象，"With great power， comes great responsibility"（能力越大，责任越大）。把“能力”换成“自由”，这句话依然成立。颓废不能改善心情，就是因为随自由而来的责任。你要为爹妈负责，因为他们省吃俭用，用自己的血汗钱供你上学；你要为自己的未来负责，不学无术、好吃懒做的你将来如何在社会上立足呢？你要为……这么多恼人的责任，让你在享受颓废时感到了不安与自责，于是你开始下意识地推卸责任，把责任推给“迷茫”是个好办法。本来嘛，在十字路口上，面对Linux, Windows, 软件、硬件、程序开发，网络管理……不知道往那边走，难道不该迷茫吗？
  
  其实，不知道为什么上学，不知道该学些什么，不知道该向哪个方向发展，不知道以后要去干什么……这些个不知道并不可怕。大学四年要解决的最主要问题就是寻找方向，摆脱迷茫。大学者，博大之学问也，本就该无所不包。Linux, Windows, 软件、硬件、程序开发，网络管理……甚至历史、地理、文学、艺术……这些都可以是你的候选方向。进了计信学院，不等于把一生卖给了IT行业，你还有足够多的时间和机会来自由选择未来的道路。
  
  那么站在这群山脚下，仰望众多的山头，你该爬向哪一座呢？在你犹豫不决的时候，零星几个不迷茫的同学已经开始攀登了。望着他们渐行渐远的背影，迷茫的人群也会有一丝骚动，少数人会跟上去。而多数人跟了两步，就停了下来，说“这山头没劲，不是我的方向”，于是就地坐下，开始玩游戏，逃课，喝酒……

  上学就像爬山，对于一个本科生来说，爬上哪个山头并不重要，重要的是攀登的过程。在这个过程中，你会锻炼出强健的体魄，顽强的毅力，会培养出克服困难的经验和自信。当你爬上山顶时，如果发现这个山头不是你理想中的顶点，那么以你强健的体魄、顽强的毅力、和丰富的经验，你可以轻松而自信地去攀登任何你心目中的高峰。
  
  也就是说，上大学只有简简单单的两个任务，一是找方向；二是在找方向的过程中，锻炼素质，磨练意志，培养能力。而完成这两个任务只有一个办法，那就是令你痛苦不堪的学习。在攀登书山，泛舟学海的过程中，你会获得良好的学习习惯，出色的学习能力，坚韧不拔的毅力，战胜困难的自信和勇气。这些素质比你在任何一门课上学到的知识都更重要。你那些毕了业的师哥师姐们应该跟你说过了，课堂上的知识如果能在工作中用到百分之五，那你就算是幸运的了。不要为那没用到的百分之九十五叹气。如果你学到的东西百分之百都能用到工作中，那只能说明你花了四年的时间和学费，却买了个技校的文凭！

  上大学的目的本来就不是为了换取饭碗，至少不只是为了饭碗。不念书，或没机会念书的民工兄弟们都饿不死，你却要花钱来为饭碗而读书，那不是很扯淡吗？上大学是为了提高一下基本素质。在学习的过程中培养起来的“习惯、能力、毅力、自信、勇气”，可以使你站得比技校里出来的“螺丝钉”们更高些，看得比他们更远些，思维比他们更敏锐、深入、独立些。而这些素质是非要在勤学苦练中才能获得的。旷课玩游戏的同学，你的问题真的是迷茫吗？说“这山头没劲，不是我的方向”的同学，你的问题真的是兴趣吗？显然不是，你们的问题是懒惰。迷茫、兴趣只不过是你畏难、偷懒、怠惰、颓废的借口罢了。

  好吧，如果你否认自己懒惰，真的很迷茫，不知道有力气该怎么使，不知道该学什么好，那么听我的，把数学、语文、英语学好。这些基础课程代表着你的基本素质。如果你能把它们学好，那意味着你不仅有了大学生的基本素质，而且你已经锻炼出了很不错的学习能力。如果你不懒惰，那么就从这里开始努力吧。

* 实用
  至于学什么比较实用，在我看都是瞎掰。别人说这个实用，大家就都一窝蜂地去学这个。而学了这个“实用”东西的人就真的有好前景了吗？恐怕不是。首先，技术是在不断更新的，今年热门而实用的东西，明年就可能乏人问津了；其次，大家一窝蜂地实用，就意味着千军万马挤独木桥的局面，前景堪忧。

  所以，在你为学什么比较实用而犯愁的时候，也许你已经想偏了。也许问题根本就不在于学什么比较实用。追求“实用”是一种看起来很“安全”的做法。可是，单纯地为了文凭，为了“实用”，为了饭碗而读书，都是很乏味、扫兴的事情，都是在很“安全”地浪费生命。既然连没读过书的民工兄弟们都没饿死，那么你有必要为“安全”而读书吗？为什么不试试为兴趣，为快乐而读书呢？快乐本就是人生追求的目标啊，可你正在为“实用”而放弃它，多么奇怪的事情啊。

我似乎听见有人反驳说“快乐不能当饭吃”。这话听起来很有“危机感”。而且危机似乎就来自于“不实用的快乐读书”。花四年的时间，看了大量闲书，学了一堆没用的东西，很快乐，可是实用的课程却被忽视了，所以毕业后肯定找不到工作。这话听起来很像那么一回事吧。可是，我告诉你，威胁你饭碗的不是“读闲书”，而是“不读书”。换言之，就是懒惰。

“我怎么懒惰了？我在努力学习那几门实用的课程啊。”没错，从大一进校门开始，我们的教师就在给学生灌输“饭碗思维”，灌输所谓“一招鲜，吃遍天”。既然一招鲜就够了，那还学习那么多干什么？当这种“多学无用”的态度被潜移默化地传递给学生的时候，“这门课没用，我不学”，“那门课没兴趣，我也不学”的现象就泛滥开了。而且不学习有了充分的理由，“因为没用，没兴趣”嘛。于是懒惰成了天经地义的事情。抱着如此消极的态度来学习，你能学好什么呢？连你认为实用的东西你也不可能学好。就是这种“天经地义”的态度才真正威胁到了你的饭碗。

学习是一个“过程”，一个训练的过程。通过这个过程，你才能获得“能力”。当你“只学那几样实用手艺”的时候，你就最大限度地缩减了学习的过程，也就只能获得最少的能力。这才是你的“饭碗危机”。

说到“当饭吃”这个话题，我非常赞同王朔的一句话，“信仰不能当饭吃，所以不重要。民主不能当饭吃，所以不重要。自由不能当饭吃，所以不重要。原则不能当饭吃，所以不重要。对于中国人来讲，不能当饭吃的都不重要。我们信奉了猪的生活原则，于是乎我们也得到了猪的命运 --- 迟早给别人当饭吃”。

我们都承认特立独行、与众不同比较酷，但轮到自己，却不敢去做点与众不同的事，甚至不敢有点与众不同的想法。只敢随着大家过“安全”、“实用”的日子。在“安全”、“实用”的日子里，只敢用一点另类的衣饰来展示一下说“我愿意酷”。如果你真的愿意酷，那么你得多花费些力气，你要在人格上培养出独立的思想，在学习上锻炼出顽强的毅力，在做事上还要有实践想法的勇气。这年头，“实用”压抑了思想，没了思想，人还成其为人吗？人没有马跑得快，没有鱼游得远，没有鹰飞得高……人唯一可以拿来炫耀的就是一个自以为聪明的大脑了。而你又懒于用大脑思考，那么岂不是禽兽不如了吗？一个禽兽不如的人，还有什么可酷的呢？

  蔡元培和胡适之的北大，是一个“思想自由，兼容并包”的地方，是一个培养“人”的地方。而看看现在的大学在培养什么？培养的是所谓“专才”，说白了就是不需要思想的“专业工具”，是一颗颗实用的“螺丝钉”。螺丝钉当然是禽兽不如的了。人家不拿咱当人看，也就罢了。咱自己如果也一窝蜂地去“实用”，岂不是不拿自己当人看吗？
* 考证
  有同学说“考证本身不是坏事”。要我说，这得看你考的是什么证。如果你考的是“垃圾证”，那么绝对是坏事。尽管说“开卷有益”，尽管说你因为考证而真的努力学习了，你做的也是一件坏事，因为你纵容了办垃圾考试的骗子。考生“心甘情愿地被骗”，这让我想起一个成语“为虎作伥”。 

我抵制考证，确切地说，是抵制考垃圾证。垃圾证和假钞一样，蒙不了明白人，但拿来蒙傻子还是可以的。也许大家就是抱着这样的心理来考证的吧。大家都知道垃圾证书是一块“假敲门砖”，但还是去考，似乎“假砖”多了也能变成“真砖”一样。这让我想起“谎言重复一千次就能变成真理”。但这种“真理”还是只能用来欺骗没脑子的人。

现在，学生毕了业都感觉工作不好找，慨叹一声“人才贬值啊”。如果你这样慨叹，那么就是你错了，因为贬值的不是“人才”，而是“证书”。扛着一麻袋垃圾证的人并不是真人才，就好像扛着一麻袋假钞的人并不是真有钱一样。

那么，什么样的证是垃圾证？简而言之，“抽自己大嘴巴的证”都是垃圾证。具体说，现在大学都是官办的，那些考试中心也是官办的。现在考试中心说了“我们官办的大学培养的人才质量太差，文凭太假，同学们必须再通过了我官办的考试，拿了我发的证书，才能证明你们是合格的”。这就是“官办”在抽自己的大嘴巴。既然你认为自己办的大学太差，你就该努力去提高大学的教学质量，提高大学文凭的含金量。再办个考试算怎么回事嘛？既开医院，又开棺材铺，这是为了治病救人吗？！

那么，什么样的证不是垃圾证？简而言之，非官办的证都比较靠谱，比如CISCO、华为、红帽子、Oracle……它们就有资格说“你们培养的人才实在太矬了，必须通过了我的考试，我才承认你们的能力”。也就是说，别人抽你大嘴巴，这虽然不友好，但还算合逻辑。“官办”抽自己大嘴巴，就为了多赚一道钱，太无耻了吧？

骂了半天，我都是在骂办考试的一方，也就是“骗子”一方。而做为受害者一方呢，也就是你们这些“被骗的人”呢？你参与这些垃圾考试的目的是什么呢？为什么你一次一次又一次地上当呢？很难相信，你的被骗不是“心甘情愿”的。你考垃圾证的目的也不光彩，就是幻想着能拿着一麻袋假钞去蒙人，不是吗？

发现了吧，这世上受骗的不都是傻瓜，很多人都是心甘情愿地上当。但你想过没有，等你真的扛一麻袋垃圾证去求职的时候，真的会有人愿意上你的当吗？

既然证书贬值了，那么你该做什么呢？很简单，拿着你的“成就”去面试，去告诉人家说“瞧，这个网站就是我设计的，它用到了什么什么技术，具备什么什么功能，达到了什么什么性能……”；去告诉人家说“瞧，这个手机应用软件就是我设计的，它在Android市场里广受好评……”；去告诉人家说“我就是什么什么开源软件的维护者，我为它贡献了多少多少行代码……”。然后再帮我扬扬名，加上一句，“我们老师说了，考一大堆垃圾证不仅是自欺欺人，而且是为虎作伥，败坏社会风气。所以，我一个证也没考，我拿我的作品来说明我的实力。”

有钱人是不会用假钞来胀满钱包的；有实力的人也犯不着用“垃圾证”来壮胆。把你考证的钱和精力用到真正的学习上，你就可以做到既不被骗，也不骗人，你就可以成为一个真正有实力、有尊严的人。

* 学习								   :noexport:
  学生可以被分为三个层次：

  捷径
  
  提问本身就是学习过程的一部分。“全看不懂……”？还是“全懒得看懂”？
  
  1. 克服懒惰，认真动手做事情。
     
     也许你觉得自己挺勤奋的了，但你得知道，你未来的竞争对手肯定不是你周围这群混日子的懒蛋。所以，别管他们懒不懒，做你自己该做的事情，不要把时间荒废掉。
  2. 学会“学习”。
     
     一方面，是学习心态。在心态上，你还嫌浮躁。另一方面是学习方法，主要是通过查资料，解决问题。这方面你还可以。
  3. 适应英文资料。
  4. 熟练使用经典开发工具（emacs, gcc...）。
  5. 操作系统技术方面的理解。
  而且，这五条的顺序是按照它们在我心中的重要程度来排列的。在我看，最重要的就是“做事情”，最不重要的就是所谓“操作系统技术”。只有那些想尽快“混个及格”的人，才会绕开前四条，直奔第五条。

而恰恰就是这个你很在意的第五条，你们在毕业以后几乎不会再碰到它。而其它四条，勤奋踏实的做事习惯，学习能力，英文能力，开发工具的使用，却是你们在今后的工作中几乎都要用到的。

学习本来就是个累活，学海无涯“苦”做舟嘛。如果轻松愉快地就“学好了”，有了成就感，那肯定是你被忽悠了。静下心来，把事情做好，把细节做好，这才是学习。
* Random Words 							   :noexport:
** 事在人为 --- 学风
   1. 压力是积累起来的
   2. 当你说学风无法转变时，你尽力了吗？
** 阿Q
   1911年的阿Q，百年后还坐在我的面前。面对我居高临下的态度，翻着白眼，心里恶狠狠地骂几句，带着得胜的感觉，下课回宿舍接着玩游戏……
** Free Thinking
   - Treasuring your rights to think and your ability to think
   - You are less than an insect without thoughts
** How to Learn?
   - Learning is the process of acquiring knowledge, needs patience
   - knowledge is broad, be curious
   - what to learn?
     - Math, Chinese, English
     - training to
       - be a fast learner
       - have habit to learn
       - be methodic
   - "I don't have interest in ..."
     - it's actually a excuse to be lazy
     - 100 or 60
** Self-esteem(ego) vs. Vanity
** Every student should know
   1. Study is not to get the answer. Study is the progress of getting the answer.
   2. Study is not to avoid an obstacle. Study is to face the problem and solve it.
   3. Study is to overcome your bad habits, e.g. can't live without a mouse.
   4. English is a matter of practice. You don't have to be smart to use it well.
   5. You don't have to pay 4 years tuition fees to buy a certificate.
   6. As a computer science student, you should know more than those newbies.
   7. What's ego (self-esteem)? What's Vanity?
   8. No try, no fail
   9. 一招鲜，吃遍天
** 偏不
   皇帝的新装
** 勇气
   - No try, no fail
   - 重要的是尝试。因为你有勇气尝试，你就有了其他人得不到的新认识，比如，同学间的团结并不如你想象的乐
     观；组织能力也不是想象中的“振臂一呼，应者云集”；下情上达也许有更好的手段……这些新认识就是你的收获。
     而那些不敢尝试的同学，他们的功夫也加深了一层，什么功夫呢？怯懦、冷漠、麻木的功夫。
   - 愤青 vs. 麻青；
     - 把怯懦与麻木当做是成熟
     - 沦陷区的顺民
   - 今天没有勇气站起来为自己的合法权益说话，明天又怎么能有勇气站出来为社会的公平公正而说话呢？
** 集体
   集体，在我看，是因为共同的利益而自愿组织起来的一群人。集体的核心不是其中的某个人，而是他们共同的利益。一旦集体的工作方向不再符合某成员的利益，他自然会选择离开。一旦这个集体不再能满足大家的利益，那么大家就散伙了。

   要求大家“关心集体”，把话说全了就是“请你暂时放弃自己的利益，来为‘集体’的利益工作”，这说法本身就违背了集体的定义。

   团队成员所做出的努力（或者牺牲），都应该是为实现自己的利益所作出的牺牲，只是碰巧这牺牲也符合团队其他成员的利益而已（如果利益冲突的话，团队就解散了）。

   西方人比中国人更有团队协作精神，道理就在这里。人家的集体是真正的集体，是符合个人利益的集体。而我们的所谓集体，大多数是假的，是违背个人意愿的，这样的集体实质上是一种绑架。绑架当然就没有协作精神了。
** 简化字
   《吕氏春秋·察今》……凡先王之法，有要于时也。时不与法俱在，法虽今而在，犹若不可法。故释先王之成法，而法其所以为法。……

   ‘变化’在这个世界上实在是再平常不过的事情了。没有变化，就没有进步。

   所以，如果是因为讨厌变化而讨厌简体字，那么……你已经老了？

   如果是因为简体字毛病太多而讨厌它，那么挺好，因为你的抱怨在推动它向毛病少的方向变化。也许它会变回到繁体字，也许……谁知道呢，反正我相信只有生命力旺盛的事物才会延续下去。﻿
