* 打算用 Linux 作为日常使用的操作系统，不做开发，哪个版本比较合适？
  
  看到这个问题，我的第一反应就是：“日常使用”这个词太含糊了。过了一会儿，我又意识到，如果认
  为“日常使用”这个词不够具体，那么我就是在或多或少地承认“Linux不能适于所有的日常使用场
  景”。
  
  做为一个有15年X龄的Debian铁杆用户，忽然发现“Linux不能适于所有的日常使用场景”，实在令我有
  点沮丧。没错，我从1998年开始接触Debian，之后我所有的办公、私人电脑上都只有Debian这一个系
  统。而且，我不是开发者。虽然我的确有一个计算机专业的硕士学历，但十几年来，除了“Hello,
  world!”之外，我几乎什么程序都没写过。我之所以写“Hello, world!”也完全是出于最基础的教学需
  要。我在大学里教《Linux应用基础》和《操作系统原理》，讲到开发的时候，好歹得举个简单的例子
  吧。一个教计算机的老师不搞开发，我知道，这很不……。但是，做为一个懒人，我也有我懒的借口。
  在天朝搞开发、搞科研，在我看就是“恭喜发财！”。如果没有经济上的困扰，我觉得把时间兑换成钞
  票是相当不划算的事情。所以，当我不得不对人家坦白说“我在事业上一事无成”的时候，我通常会向
  人家展示一下我寒暑假的骑行游记，以此证明我这些年也没白活。否则，后面的聊天……我反正脸皮厚，
  但对方会感到尴尬的。
  
  不管怎么说，我就是一个地地道道的Linux日常使用者，而且不搞开发，而且我的Debian能满足
  我几乎所有的日常需求。当然，我的日常需求也的确相当简单（上网、听歌、看片、写讲义、做幻灯
  片……）。
  
  那么，Linux到底能不能应付所有的“日常使用”场景？我觉得，能，但你很难用某一个通用的
  Linux系统来满足所有的场景。通常，你要对自己的系统做有针对性的配置，从而让它能够满足你
  的日常使用需求。于此相对照，MAC OS X基本上做到了用一个系统来满足所有的用户需求。这的确
  是它的优势所在。
  
  那么，哪个Linux品牌（发行版）最好用？严肃地说，都一样好用。不信？在十台电脑上装十个牌子的
  Linux，放到你面前，你会发现的确都很好用，也很漂亮，而且你分辨不出谁是谁。换句话说，做为普
  通用户，你不必关心“牌子”问题，因为各品牌的不同之处，不在于使用，而在于管理。Debian和
  Redhat的系统管理方式（操作命令、配置文件的格式等等）是大不相同的。而“管理”是管理员的事情，
  做为一个普通用户的确不需要去操心。如果你想成为一个管理员，你至少得先成为一个熟练用户才行
  吧。
  
  那么，如果我打定主意要用Linux了，我该装哪个牌子的系统？我觉得，你周围的熟练用户都用什么
  牌子，你就跟着用什么牌子。很显然，这样你获得帮助最方便。如果你周围没有熟练用户，那么我建
  议你用Debian，因为它
  1. 稳定性好，bug少
  2. 软件库大
  3. 社区大，Debian/Ubuntu拥有最庞大的用户群
  4. 管理（软件包的安装、卸载、升级）方式简单
  
  下面简单罗列一下我在Linux平台不能顺利完成的事情：
  - 目前国内还有不少只能用IE才能正常浏览的网站，比如我们学校的教务系统。（此处略去200脏字）
  - 大多数国内的网上银行也都是面向IE开发的。（还好，有浦发这个例外，据说广发也不错）
  - Linux平台没有原生的炒股软件，但通过WINE也还可以挺顺畅地应付。
    
  除此之外，我的Debian就只剩下优点了。当然，对于一个传统的Windows用户，他要面对的困扰远不止
  这么三条，比如说
  - 他习惯于使用MS-Office来做事情（可以尝试永中Office，或者WPS）
  - 他要QQ（可以尝试WebQQ）
  - 他要玩游戏（也许可以WINE）
  - 他要……
    
  总之，做为入门用户，而且又被天朝Windows/QQ/Baidu/360用户群包围着，又生活在防火长城之下，
  困难总会有的，但未必无法克服。
    
  Debian可能是我人生中最正确的一个选择了。干净，自由。
